WebApp/WebApp/Models/DeviceUser.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebApp.Models
{
    public class DeviceUser
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Display(Name = "Profile Picture")]
        public string ProfilePic { get; set; }

        public int? Age { get; set; }

        [EmailAddress]
        public string Email { get; set; }

        [Phone]
        public string Phone { get; set; }

        [Phone, Display(Name = "Emergency Phone")]
        public string EmergencyPhone { get; set; }

        public string Gender { get; set; }

        [Display(Name = "Swimming Skills")]
        public string SwimmingSkills { get; set; }

        public string Notes { get; set; }
        
        public int DeviceId { get; set; }

        public int? CustomerId { get; set; }

        [ForeignKey("CustomerId")]
        public virtual Customer Customer { get; set; }

    }

    
}

WebApp/WebApp/ViewModels/DeviceUserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using WebApp.Models;

namespace WebApp.ViewModels
{
    public class DeviceUserViewModel
    {
        public string Name { get; set; }

        public string ProfilePic { get; set; }

        public int? Age { get; set; }

        public string EmergencyPhone { get; set; }

        public string Gender { get; set; }

        public string SwimmingSkills { get; set; }

        public string Notes { get; set; }
    }
}

WebApp/WebApp/Controllers/DeviceUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;
using WebApp.Services;

namespace WebApp.Controllers
{
    [Authorize]
    public class DeviceUsersController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();
        private readonly BlobServices _blobServices = new BlobServices();

        // GET: DeviceUsers
        public ActionResult Index()
        {
            return View(_db.DeviceUsers.ToList());
        }

        // GET: DeviceUsers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var deviceUser = _db.DeviceUsers.Find(id);
            if (deviceUser == null)
            {
                return HttpNotFound();
            }
            return View(deviceUser);
        }

        // GET: DeviceUsers/Create
        public ActionResult Create()
        {
            ViewBag.CustomersList = new SelectList(_db.Customers.ToList(), "Id", "Name");
            return View();
        }

        // POST: DeviceUsers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DeviceUser deviceUser, HttpPostedFileBase uploadFile)
        {
            if (ModelState.IsValid)
            {
                if (uploadFile?.ContentLength > 0)
                {
                    var extension = Path.GetExtension(uploadFile.FileName);
                    if (extension?.ToLower() == ".png" || extension?.ToLower() == ".jpg"
                        || extension?.ToLower() == ".jpeg")
                    {
                        var imageName = Path.GetFileNameWithoutExtension(uploadFile.FileName);
                        imageName = Path.Combine(Server.MapPath("~/Images/") + imageName + extension);
                        uploadFile.SaveAs(imageName);

                        Upload(imageName, extension, ref deviceUser);

                        // Delete file from server after finishing 
                        GC.Collect();
                        GC.WaitForPendingFinalizers();
                        System.IO.File.Delete(imageName);
                    }
                    else
                    {
                        ViewBag.ErrorMsg = "File type not supported for upload. Available formats: .pdf, .png, .jpg, .jpeg";
                        return View("Error");
                    }

                }

                _db.DeviceUsers.Add(deviceUser);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(deviceUser);
        }

        public void Upload(string path, string extension, ref DeviceUser deviceUser)
        {
            var locPath = _blobServices.BlobUrl;
            var type = "deviceusers-profilepics";
            var imageName = deviceUser.Name + "-profilepic"+ extension;
            deviceUser.ProfilePic = locPath + type + "/" + imageName;

            _blobServices.BlobImageUpload(imageName, path, type);

        }

        // GET: DeviceUsers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var deviceUser = _db.DeviceUsers.Find(id);
            if (deviceUser == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomersList = new SelectList(_db.Customers.ToList(), "Id", "Name");
            ViewBag.DevicesList = new SelectList(_db.Devices.ToList(), "Id", "Id");
            return View(deviceUser);
        }

        // POST: DeviceUsers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DeviceUser deviceUser, HttpPostedFileBase uploadFile)
        {
            if (ModelState.IsValid)
            {
                if (uploadFile?.ContentLength > 0)
                {
                    var extension = Path.GetExtension(uploadFile.FileName);
                    if (extension?.ToLower() == ".png" || extension?.ToLower() == ".jpg"
                        || extension?.ToLower() == ".jpeg")
                    {
                        var imageName = Path.GetFileNameWithoutExtension(uploadFile.FileName);
                        imageName = Path.Combine(Server.MapPath("~/Images/") + imageName + extension);
                        uploadFile.SaveAs(imageName);

                        Upload(imageName, extension, ref deviceUser);

                        // Delete file from server after finishing 
                        GC.Collect();
                        GC.WaitForPendingFinalizers();
                        System.IO.File.Delete(imageName);
                    }
                    else
                    {
                        ViewBag.ErrorMsg = "File type not supported for upload. Available formats: .pdf, .png, .jpg, .jpeg";
                        return View("Error");
                    }

                }

                _db.Entry(deviceUser).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(deviceUser);
        }

        // GET: DeviceUsers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var deviceUser = _db.DeviceUsers.Find(id);
            if (deviceUser == null)
            {
                return HttpNotFound();
            }
            _db.DeviceUsers.Remove(deviceUser);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApp/WebApp/Views/DeviceUsers/Create.cshtml
@model WebApp.Models.DeviceUser

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","DeviceUsers",FormMethod.Post,
    new { enctype = "multipart/form-data", data_ajax = "false" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>DeviceUser</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfilePic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="uploadFile" name="uploadFile" type="file" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmergencyPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmergencyPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmergencyPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.Gender, "Male") Male
                <br />
                @Html.RadioButtonFor(model => model.Gender, "Female") Female
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SwimmingSkills, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SwimmingSkills, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SwimmingSkills, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Customer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CustomerId, ViewBag.CustomersList as SelectList, "-select customer-", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApp/WebApp/Views/DeviceUsers/Details.cshtml
@model WebApp.Models.DeviceUser

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DeviceUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Device Id")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeviceId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfilePic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfilePic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmergencyPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmergencyPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SwimmingSkills)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SwimmingSkills)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApp/WebApp/Views/DeviceUsers/Edit.cshtml
@model WebApp.Models.DeviceUser

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit","DeviceUsers",FormMethod.Post, 
    new { enctype = "multipart/form-data", data_ajax = "false" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>DeviceUser</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.DeviceId)
        @Html.HiddenFor(model => model.ProfilePic)
        
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Customer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CustomerId, ViewBag.CustomersList as SelectList, "-select customer-", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfilePic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="uploadFile" name="uploadFile" type="file" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmergencyPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmergencyPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmergencyPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.Gender, "Male") Male
                <br />
                @Html.RadioButtonFor(model => model.Gender, "Female") Female
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SwimmingSkills, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SwimmingSkills, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SwimmingSkills, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApp/WebApp/Views/DeviceUsers/Index.cshtml
@model IEnumerable<WebApp.Models.DeviceUser>

@{
    ViewBag.Title = "Devices Users";
}

<h2>Devices Users</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.Label("Device Id")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.Label("Customer Name")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DeviceId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Customer.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>